import React, { useState } from 'react';
import { useNavigate } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useCart } from '../context/CartContext';
import { CheckCircle2, CreditCard, Lock, ShieldCheck, Truck } from 'lucide-react';

const Money = ({ value }) => <>₹{value.toLocaleString('en-IN')}</>;
export default function Checkout() {
  const navigate = useNavigate(); const { cart, cartSubtotal, deliveryFee, cartTotal, createOrder } = useCart(); const { currentUser } = useAuth();
  const [shippingInfo, setShippingInfo] = useState({ fullName: currentUser?.name || '', phone: currentUser?.phone || '', email: currentUser?.email || '', address: '', city: 'Bengaluru', state: 'Karnataka', pincode: '560038', paymentMethod: 'COD' });
  const update = (field) => (event) => setShippingInfo({ ...shippingInfo, [field]: event.target.value });
  const submit = (event) => { event.preventDefault(); if (!shippingInfo.address || !shippingInfo.phone) { alert('Please complete your delivery address and phone number.'); return; } createOrder(shippingInfo); navigate('/orders'); };
  if (!cart.length) return <main className="purchase-page container-custom"><div className="empty-bag"><CheckCircle2 size={40} /><p className="eyebrow">No order to place</p><h1>Your bag is empty.</h1><button onClick={() => navigate('/collections')} className="button-primary">Browse the collection</button></div></main>;
  return <main className="checkout-page container-custom"><header className="purchase-header"><div><p className="eyebrow">Almost yours</p><h1>Secure checkout</h1></div><div className="checkout-steps"><span className="done">Bag</span><i /><span className="active">Delivery</span><i /><span>Payment</span></div></header>
    <form onSubmit={submit} className="checkout-layout"><section className="checkout-form"><div className="form-section"><div className="form-heading"><span>01</span><div><h2>Delivery details</h2><p>Where would you like your handloom saree delivered?</p></div></div><div className="field-grid"><label className="full-field">Full name <input required value={shippingInfo.fullName} onChange={update('fullName')} placeholder="Recipient’s full name" /></label><label>Phone number <input required type="tel" value={shippingInfo.phone} onChange={update('phone')} placeholder="+91 00000 00000" /></label><label>Email address <input type="email" value={shippingInfo.email} onChange={update('email')} placeholder="name@example.com" /></label><label className="full-field">Address <textarea required rows="3" value={shippingInfo.address} onChange={update('address')} placeholder="House / Flat no., street, landmark" /></label><label>City <input required value={shippingInfo.city} onChange={update('city')} /></label><label>State <input required value={shippingInfo.state} onChange={update('state')} /></label><label>Pincode <input required value={shippingInfo.pincode} onChange={update('pincode')} /></label></div></div>
      <div className="form-section"><div className="form-heading"><span>02</span><div><h2>Payment method</h2><p>Select how you’d like to pay.</p></div></div><div className="payment-options"><label className={shippingInfo.paymentMethod === 'COD' ? 'selected' : ''}><input type="radio" name="payment" checked={shippingInfo.paymentMethod === 'COD'} onChange={() => setShippingInfo({ ...shippingInfo, paymentMethod: 'COD' })} /><span className="payment-icon"><Truck size={19} /></span><span><strong>Cash on delivery</strong><small>Pay when your order arrives.</small></span><b>COD</b></label><label className={shippingInfo.paymentMethod === 'ONLINE' ? 'selected' : ''}><input type="radio" name="payment" checked={shippingInfo.paymentMethod === 'ONLINE'} onChange={() => setShippingInfo({ ...shippingInfo, paymentMethod: 'ONLINE' })} /><span className="payment-icon"><CreditCard size={19} /></span><span><strong>UPI, card or net banking</strong><small>Secure online payment.</small></span><b>Online</b></label></div></div></section>
      <aside className="checkout-summary"><p className="eyebrow">Your order</p><h2>{cart.length} handloom {cart.length === 1 ? 'piece' : 'pieces'}</h2><div className="checkout-items">{cart.map(({ saree, quantity }) => <div key={saree.id}><img src={saree.images[0]} alt="" /><p><strong>{saree.name}</strong><span>Qty {quantity}</span></p><b><Money value={saree.price * quantity} /></b></div>)}</div><div className="summary-lines"><p><span>Subtotal</span><strong><Money value={cartSubtotal} /></strong></p><p><span>Delivery</span>{deliveryFee ? <strong><Money value={deliveryFee} /></strong> : <strong className="free-delivery">Complimentary</strong>}</p></div><div className="summary-total"><span>Total payable</span><strong><Money value={cartTotal} /></strong></div><button className="button-primary summary-button" type="submit"><Lock size={16} /> Place secure order</button><p className="summary-note"><ShieldCheck size={15} /> Your details are securely protected.</p></aside>
    </form></main>;
}
